"""empty message

Revision ID: 2af635d2d9e4
Revises: 424063d88e0c
Create Date: 2021-08-15 16:57:59.880536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af635d2d9e4'
down_revision = '424063d88e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Developer', ['username'])
    op.alter_column('Resource', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Resource', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'Developer', type_='unique')
    # ### end Alembic commands ###
