"""empty message

Revision ID: 424063d88e0c
Revises: 545c268dce67
Create Date: 2021-08-07 17:11:32.538471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424063d88e0c'
down_revision = '545c268dce67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resource', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resource', 'img_url')
    # ### end Alembic commands ###
