"""empty message

Revision ID: 545c268dce67
Revises:
Create Date: 2021-08-05 01:50:44.168710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545c268dce67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Developer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Resource',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('note', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Booking',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('developer_id', sa.Integer(), nullable=False),
                    sa.Column('resource_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column(
                        'expected_duration_hours',
                        sa.Integer(),
                        nullable=True
                    ),
                    sa.ForeignKeyConstraint(
                        ['developer_id'],
                        ['Developer.id']
                    ),
                    sa.ForeignKeyConstraint(
                        ['resource_id'],
                        ['Resource.id']
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Booking')
    op.drop_table('Resource')
    op.drop_table('Developer')
    # ### end Alembic commands ###
